services:
  server:
    build: server
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:8080"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
  client:
    build: client
    ports:
      - 8501:8501
    # depends_on:
    #   server:
    #     condition: service_healthy
  